### ISSUE TITLE
OCTET STRING as UFT8 STRING ?

### ISSUE THREAD

**Issue by t-geindre** [sop/asn1#15]
Hi,
First, I'd like to thank you for this amazing library, it saved me a lot of time.

I'am trying to decode ASN1/DER data coming from Itunes In-App purchase receipt. Here is the schema I've found in [their documentation](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html):

```
ReceiptModule DEFINITIONS ::=
--
BEGIN
 
ReceiptAttribute ::= SEQUENCE {
type    INTEGER,
version INTEGER,
value   OCTET STRING
}
 
Payload ::= SET OF ReceiptAttribute
 
END
```
As far as I understand this, all value fields are supposed to contain `OCTET STRING`. But, in the [receipt fields documentation](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html), there is different types such as `UTF8STRING`, `IA5STRING`, `INTEGER`... I think they use `OCTET STRING` actually containing other data types.

But, if I try to get an integer on an octet string field, I get the following error:
```
Uncaught UnexpectedValueException: INTEGER expected, got primitive OCTET STRING.
```

And, if I read the value as an `OCTET STRING`, I get a weird string made of 3 non printable chars...

Any idea?

I have to say I'm very new to this kind of file and I might miss something very obvious.

**Comment by t-geindre** [comment]
Here is file example I'm trying to decode:
http://nostalgeek.org/5d3b21122c2a4.asn1

**Comment by sop** [comment]
Hi!

Sorry that i haven't had time to look into this.
Seems that value must be interpreted differently depending on the type field. Eg. when type is 2, value contains a DER encoded data of an UTF8STRING.

Here's an example:
```
$data = file_get_contents(__DIR__ . '/5d3b21122c2a4.asn1');
$set = Element::fromDER($data);
foreach ($set as $el) {
    /** @var UnspecifiedType $el */
    $receipt = $el->asSequence();
    $type = $receipt->at(0)->asInteger()->intNumber();
    $value = $receipt->at(2)->asOctetString()->string();
    if ($type == 2) {
        echo UTF8String::fromDER($value)->string() . "\n";
    }
}
```

**Comment by t-geindre** [comment]
Thank you **very much**, it works exactly as expected!
