### ISSUE TITLE
PHP7.2: Calling assert() with a string argument is deprecated

### ISSUE THREAD

**Issue by afk11** [sop/asn1#3]
Looks like this pattern is used throughout the codebase - I'll draft up a PR for this soon if I get a chance

eg:

/lib/ASN1/Element.php on line 213
/lib/ASN1/Component/Identifier.php on line 87
/lib/ASN1/Component/Length.php on line 52

**Comment by sop** [comment]
Thanks for the heads up! I think we could as well drop the pre 7.0 support from future releases and add scalar type hinting. I'm quite bound to other projects atm, but will look into this in the future.
