### ISSUE TITLE
Identifiers of 'application' class

### ISSUE THREAD

**Issue by 3DFace** [sop/asn1#7]
Hi!

Just tried this lib to parse SNMP packets. 
No luck. Seems like decoding data with identifiers of 'application' class does not supported.

Have you any plans to implement it?
Any workarounds? Some kind of extension points or hacks that I can use?

Thank you!

**Comment by sop** [comment]
Hi!

I haven't yet encountered a case having other than universal tags. Could you provide me with a DER dump of the packet you're trying to decode and i'll have a look at it.

**Comment by 3DFace** [comment]
Here is a packet hex:

`302D02010004067075626C6963A2200204659FE6C50201000201003012301006082B0601020101030043040B1608C5`

It is SNMP message with `GetResponse` PDU.

The problem in the tail: `43040B1608C5`. I guess it is `['app-type with tag 3', 'length 4', 'data']`.

`Element::fromDER(hex2bin('43040B1608C5'));` throws `APPLICATION 3 not implemented.`

SNMP defines several application-specific types. You can look at [RFC 1155](https://tools.ietf.org/html/rfc1155#section-3.2.3) for more info.

Thank you for attention!

**Comment by sop** [comment]
Thanks! I did some research and implemented support for application specific types.

Decoding now yields an [`ApplicationType`](https://github.com/sop/asn1/blob/master/lib/ASN1/Type/Tagged/ApplicationType.php) object, that can be handled as explicitly or implicitly tagged element depending on the context.

You can encode application types to DER by wrapping an element into [`ExplicitlyTaggedType`](https://github.com/sop/asn1/blob/master/lib/ASN1/Type/Tagged/ExplicitlyTaggedType.php) or [`ImplicitlyTaggedType`](https://github.com/sop/asn1/blob/master/lib/ASN1/Type/Tagged/ImplicitlyTaggedType.php) and passing a [`Identifier::CLASS_APPLICATION`](https://github.com/sop/asn1/blob/master/lib/ASN1/Component/Identifier.php#L18) as a `$class` parameter.

So, here's a working example of the data you provided:
```
$der = hex2bin('43040B1608C5');
$ticks = UnspecifiedType::fromDER($der)
    ->asApplication()
    ->asImplicit(Element::TYPE_INTEGER)
    ->asInteger()
    ->intNumber();
```

I figured the tag 3 is a TimeTicks type:
```
TimeTicks ::=
  [APPLICATION 3]
    IMPLICIT INTEGER (0..4294967295)
```

Can you pull the master for testing, or should i tag a release?

**Comment by 3DFace** [comment]
I've pulled the master and have done some trivial testing - it seems like it works as expected. 
I need to go deeper into that encoding/decoding staff to be sure. But for now I'm happy with your additions. 

Thank you for such quick help!

**Comment by 3DFace** [comment]
Hi again!

I've finished my diving and can conclude that current API satisfies all my needs in work with application-specific types. At least the cases I've encountered in SNMP encoding/decoding tasks.

So I'm closing the issue. Thank you!
